CREATE TABLE HARI_CUSTOMER_TABLE(ID INT NOT NULL,NAME VARCHAR(250),PASSWORD VARCHAR(250))

INSERT INTO HARI_CUSTOMER_TABLE VALUES(1,'Hari','1234')
INSERT INTO HARI_CUSTOMER_TABLE VALUES(2,'Arun','1431')
INSERT INTO HARI_CUSTOMER_TABLE VALUES(3,'Mugen','3210')

SELECT * FROM HARI_CUSTOMER_TABLE
SELECT * FROM HARI_STOCKAVB_TABLE

CREATE TABLE HARI_STOCKAVB_TABLE(ID INT NOT NULL,STOCKNAME VARCHAR(250),AVAILABLESTOCK INT)



INSERT INTO HARI_STOCKAVB_TABLE VALUES(1,'Gold',2000)
INSERT INTO HARI_STOCKAVB_TABLE VALUES(2,'Silver',3000)
INSERT INTO HARI_STOCKAVB_TABLE VALUES(3,'Platinum',3000)
INSERT INTO HARI_STOCKAVB_TABLE VALUES(4,'Bronze',4000)



